### ISSUE TITLE
Low completeness with high QV

### ISSUE THREAD

**Issue by evolgen** [marbl/merqury#1] opened 2020-03-21 01:24 UTC
Hi Arang,

Thanks for the wonderful software.
We were trying to apply it to our fish data but the results look a bit off.
The QV stats are as follows -
referencegenome 2207970 963657040       39.6167 0.000109226

However the completeness looks very low -
referencegenome all     624153086       2400034559      26.006

I noticed that you declare $asm.solid.meryl. Is it generated from filt.sh or am I missing something here?
For some reason the filt.sh generates a read.filt with a value of 0 - ploidy, depth and boundary are all 0. The histogram of my illumina reads db is as follows -
1       1669096430
2       730938129
Is there any missing output prefix in #line52 of spectra-cn.sh?

We have larger nodes available than multiple smaller ones hence need run it as a single node job rather than a batch job.

**Comment by arangrhie** [comment] 2020-03-21 01:59
Hi, @evolgen!

QV score and completeness are not coupled. It is possible to get high QV with low completeness.

It seems like the filt.sh got confused when deciding the cutoff.
The `filt.sh` finds the first minimum threshold for filtering out erroneous k-mers.
Wonder how your histogram looks like?
Would be nice if you could share the full histogram.

Try
```
echo -e "Copies\tkmer_multiplicity\tCount" > test.hist
awk '{print "read\t"$0}' read.hist >> test.hist 
Rscript $MERQURY/plot/plot_spectra_cn.R -f test.hist -o test.hist -t line
```
This will generate `test.hist.ln.png`. Check if there is a visible peak.
Or, you could use [genomescope](http://qb.cshl.edu/genomescope/), giving your read.hist.
You can share the genomescope link here if you'd like.

**Comment by arangrhie** [comment] 2020-03-21 02:05
> Is there any missing output prefix in #line52 of spectra-cn.sh?

[out] is optional. It symlinks the read.gtN.meryl to the given output name.
We don't need this on spectra-cn. :)

>We have larger nodes available than multiple smaller ones hence need run it as a single node job rather than a batch job.

That's absolutely fine. Non-trio version only runs spectra-cn.sh.
The maximum number of cpus that Meryl uses are 64.

You can tune merqury.sh if you have trios, see the [here](https://github.com/marbl/merqury#how-to-parallelize) for dependencies.

**Comment by evolgen** [comment] 2020-03-21 17:56
Hi Arang,

Thanks for the swift response.
I was wondering why the completeness form Kmers was very low though BUSCO scores were >95% complete.
I did not not the prefix was optional, thanks for that👍 I assumed all meryl based processes needed strict prefixes.

We do not have any trios though, but everything seems to run smoothly until now. I have added the genomescope and merqury based kmer plots below.
![plot](https://user-images.githubusercontent.com/47459143/77233072-4feb2900-6b62-11ea-9087-c724ecb28743.png)
![refgenome meryl referencegenome spectra-cn ln](https://user-images.githubusercontent.com/47459143/77233073-524d8300-6b62-11ea-98c2-eb137f6229a9.png)
 
I assume there is something wrong in the kmer histogram step from my end. 

Cheers,
Rohit

**Comment by arangrhie** [comment] 2020-03-23 03:54
Hi Ronin,

Is your read meryl db named as `read.meryl`?
I may have to clarify the README a bit more.. Meryl assumes all meryl dbs to be named with `.meryl`.
Let me know if renaming fixes the problem!

**Comment by evolgen** [comment] 2020-03-23 17:22
Hi Arang,

I had this problem earlier, not naming the database as read.meryl. But I created a folder with that name and move all the files. I even reran the process from counting to merqury to make sure, unfortunately the same results, only two kmers are produced in the histogram.

**Comment by arangrhie** [comment] 2020-03-23 19:44
I am a bit confused. Sorry, I can't reproduce your problem. :(

The histogram used for genomescope seems fine. Was that generated with `meryl histogram`?
Can you share the meryl db you've generated, or the illumina dataset?

**Comment by evolgen** [comment] 2020-03-23 21:02
Hi Arang,

The genomescope was from Jellyfish kmer counting. 

I am happy to share the illumina db - I will upload it somewhere accessible, can you please provide an email ID. Thanks for the help :)

**Comment by arangrhie** [comment] 2020-03-23 22:12
Sure! Share it with rhiea [ at ] nih . gov .
Also, if available, sharing your logs under `logs/` might help me debug.

**Comment by evolgen** [comment] 2020-03-24 04:30
Hi Arang,

I shared them, along with the log file.
I used a meryl union command on the input files, this might be the problem.

**Comment by arangrhie** [comment] 2020-03-24 18:12
oh, yeah, you need `union-sum`. `union` is counting how many meryl dbs you see the k-mers. @brianwalenz can better explain. :)

**Comment by evolgen** [comment] 2020-03-24 18:16
oh crap! I messed up that part of the workflow. I will rerun meryl with union-sum or simply a super fastq of all sequences. Sorry about the issue, I will update you once I have the results from the run and close it.

**Comment by arangrhie** [comment] 2020-03-24 19:25
Cool! Keep us updated.

**Comment by evolgen** [comment] 2020-03-25 01:43
Got the updated run, these are the completeness metrics -
referencegenome all     623115314       675509112       92.2438

Below is the kmer histogram -
![refgenome2 meryl referencegenome spectra-cn fl](https://user-images.githubusercontent.com/47459143/77493049-4cc09900-6dff-11ea-81b1-dd0d2e963c61.png)

Thanks for the help  👍

**Comment by arangrhie** [comment] 2020-03-26 20:51
Awesome! Glad it was an easy fix :)
Seems like a nice haploid representation, except those duplications that could be removed (blue peak ~40x). Try something like [purge_dups](https://github.com/dfguan/purge_dups) and see if that helps to reduce the 2-copy k-mers.

Will close the issue.

Stay safe!

**Closed by arangrhie** 2020-03-26 20:51 UTC

**Comment by evolgen** [comment] 2020-03-26 21:04
Thanks a ton Arang.
Purge_dups was already performed on this genome - I added the duplications after scaffolding in the final assembly file, hence the blue peak.
Take care!!!
