### ISSUE TITLE
hap_blot

### ISSUE THREAD

**Issue by duhuipeng** [marbl/merqury#34] opened 2021-03-09 00:48 UTC
dear author
I finished hap_blot this step, why is it like this, what caused it?
![image](https://user-images.githubusercontent.com/58722433/110400974-a9ba6b00-80b3-11eb-8ebf-f10f8fd9589b.png)
I found out in the log that this step was not wrong

**Comment by arangrhie** [comment] 2021-03-09 03:02
This plot is showing how many maternal hapmers are found in each contig/scaffold in the assemblies.
Have you switched your father_purged and purged_mo assembly labelings, or the parental db naming?

**Comment by duhuipeng** [comment] 2021-03-09 08:34
Dear author
The code I run is as follows:
./merqury.sh Son.meryl Mother.hapmer.meryl Father.hapmer.meryl father_purged.fasta purged_mo.fasta test

But I didn't found  error in Hap_blot.sh in log file,Looking forward to your advice,What's wrong with me
Here is my log file for this step
[test.blob.log](https://github.com/marbl/merqury/files/6106987/test.blob.log)

**Comment by arangrhie** [comment] 2021-03-10 00:56
Double check the assembly was properly named, as well as the kmer dbs. The Merqury plot is naming the axises following the input file. The blob plot is telling me your assembly is completely swapped, when the hapmers are correct.

**Comment by arangrhie** [comment] 2021-03-15 17:03
Closing this issue as this is not a bug in merqury.

**Closed by arangrhie** 2021-03-15 17:03 UTC

**Comment by duhuipeng** [comment] 2021-03-20 00:52
Dear author
![image](https://user-images.githubusercontent.com/58722433/111854265-41904280-8959-11eb-9053-6a949c542cef.png)
Why is the picture like this?Hope to get your advice
